import pygame
from entities import PisoAzul
from entities import PisoVermelho
from entities import PisoPreto
from entities import PisoBranco


objectGroup = pygame.sprite.Group()
white_floorGroup = pygame.sprite.Group()
black_floorGroup = pygame.sprite.Group()
blue_floorGroup = pygame.sprite.Group()
red_floorGroup = pygame.sprite.Group()


#Atribuição dos pisos que podem ser desenhados na linha 1
fw11,   fk11,   fb11,   fr11   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw12,   fk12,   fb12,   fr12   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw13,   fk13,   fb13,   fr13   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw14,   fk14,   fb14,   fr14   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw15,   fk15,   fb15,   fr15   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw16,   fk16,   fb16,   fr16   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw17,   fk17,   fb17,   fr17   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw18,   fk18,   fb18,   fr18   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw19,   fk19,   fb19,   fr19   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw110,  fk110,  fb110,  fr110  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw111,  fk111,  fb111,  fr111  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw112,  fk112,  fb112,  fr112  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw113,  fk113,  fb113,  fr113  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw114,  fk114,  fb114,  fr114  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw115,  fk115,  fb115,  fr115  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 2
fw21,   fk21,   fb21,   fr21   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw22,   fk22,   fb22,   fr22   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw23,   fk23,   fb23,   fr23   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw24,   fk24,   fb24,   fr24   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw25,   fk25,   fb25,   fr25   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw26,   fk26,   fb26,   fr26   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw27,   fk27,   fb27,   fr27   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw28,   fk28,   fb28,   fr28   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw29,   fk29,   fb29,   fr29   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw210,  fk210,  fb210,  fr210  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw211,  fk211,  fb211,  fr211  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw212,  fk212,  fb212,  fr212  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw213,  fk213,  fb213,  fr213  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw214,  fk214,  fb214,  fr214  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw215,  fk215,  fb215,  fr215  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 3
fw31,   fk31,   fb31,   fr31   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw32,   fk32,   fb32,   fr32   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw33,   fk33,   fb33,   fr33   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw34,   fk34,   fb34,   fr34   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw35,   fk35,   fb35,   fr35   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw36,   fk36,   fb36,   fr36   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw37,   fk37,   fb37,   fr37   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw38,   fk38,   fb38,   fr38   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw39,   fk39,   fb39,   fr39   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw310,  fk310,  fb310,  fr310  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw311,  fk311,  fb311,  fr311  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw312,  fk312,  fb312,  fr312  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw313,  fk313,  fb313,  fr313  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw314,  fk314,  fb314,  fr314  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw315,  fk315,  fb315,  fr315  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 4
fw41,   fk41,   fb41,   fr41   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw42,   fk42,   fb42,   fr42   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw43,   fk43,   fb43,   fr43   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw44,   fk44,   fb44,   fr44   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw45,   fk45,   fb45,   fr45   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw46,   fk46,   fb46,   fr46   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw47,   fk47,   fb47,   fr47   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw48,   fk48,   fb48,   fr48   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw49,   fk49,   fb49,   fr49   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw410,  fk410,  fb410,  fr410  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw411,  fk411,  fb411,  fr411  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw412,  fk412,  fb412,  fr412  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw413,  fk413,  fb413,  fr413  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw414,  fk414,  fb414,  fr414  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw415,  fk415,  fb415,  fr415  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 5
fw51,   fk51,   fb51,   fr51   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw52,   fk52,   fb52,   fr52   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw53,   fk53,   fb53,   fr53   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw54,   fk54,   fb54,   fr54   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw55,   fk55,   fb55,   fr55   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw56,   fk56,   fb56,   fr56   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw57,   fk57,   fb57,   fr57   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw58,   fk58,   fb58,   fr58   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw59,   fk59,   fb59,   fr59   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw510,  fk510,  fb510,  fr510  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw511,  fk511,  fb511,  fr511  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw512,  fk512,  fb512,  fr512  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw513,  fk513,  fb513,  fr513  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw514,  fk514,  fb514,  fr514  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw515,  fk515,  fb515,  fr515  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 6
fw61,   fk61,   fb61,   fr61   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw62,   fk62,   fb62,   fr62   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw63,   fk63,   fb63,   fr63   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw64,   fk64,   fb64,   fr64   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw65,   fk65,   fb65,   fr65   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw66,   fk66,   fb66,   fr66   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw67,   fk67,   fb67,   fr67   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw68,   fk68,   fb68,   fr68   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw69,   fk69,   fb69,   fr69   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw610,  fk610,  fb610,  fr610  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw611,  fk611,  fb611,  fr611  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw612,  fk612,  fb612,  fr612  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw613,  fk613,  fb613,  fr613  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw614,  fk614,  fb614,  fr614  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw615,  fk615,  fb615,  fr615  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 7
fw71,   fk71,   fb71,   fr71   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw72,   fk72,   fb72,   fr72   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw73,   fk73,   fb73,   fr73   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw74,   fk74,   fb74,   fr74   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw75,   fk75,   fb75,   fr75   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw76,   fk76,   fb76,   fr76   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw77,   fk77,   fb77,   fr77   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw78,   fk78,   fb78,   fr78   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw79,   fk79,   fb79,   fr79   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw710,  fk710,  fb710,  fr710  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw711,  fk711,  fb711,  fr711  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw712,  fk712,  fb712,  fr712  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw713,  fk713,  fb713,  fr713  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw714,  fk714,  fb714,  fr714  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw715,  fk715,  fb715,  fr715  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 8
fw81,   fk81,   fb81,   fr81   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw82,   fk82,   fb82,   fr82   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw83,   fk83,   fb83,   fr83   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw84,   fk84,   fb84,   fr84   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw85,   fk85,   fb85,   fr85   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw86,   fk86,   fb86,   fr86   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw87,   fk87,   fb87,   fr87   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw88,   fk88,   fb88,   fr88   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw89,   fk89,   fb89,   fr89   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw810,  fk810,  fb810,  fr810  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw811,  fk811,  fb811,  fr811  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw812,  fk812,  fb812,  fr812  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw813,  fk813,  fb813,  fr813  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw814,  fk814,  fb814,  fr814  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw815,  fk815,  fb815,  fr815  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 9
fw91,   fk91,   fb91,   fr91   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw92,   fk92,   fb92,   fr92   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw93,   fk93,   fb93,   fr93   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw94,   fk94,   fb94,   fr94   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw95,   fk95,   fb95,   fr95   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw96,   fk96,   fb96,   fr96   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw97,   fk97,   fb97,   fr97   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw98,   fk98,   fb98,   fr98   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw99,   fk99,   fb99,   fr99   = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw910,  fk910,  fb910,  fr910  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw911,  fk911,  fb911,  fr911  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw912,  fk912,  fb912,  fr912  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw913,  fk913,  fb913,  fr913  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw914,  fk914,  fb914,  fr914  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw915,  fk915,  fb915,  fr915  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 10
fw101,  fk101,  fb101,  fr101  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw102,  fk102,  fb102,  fr102  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw103,  fk103,  fb103,  fr103  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw104,  fk104,  fb104,  fr104  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw105,  fk105,  fb105,  fr105  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw106,  fk106,  fb106,  fr106  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw107,  fk107,  fb107,  fr107  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw108,  fk108,  fb108,  fr108  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw109,  fk109,  fb109,  fr109  = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1010, fk1010, fb1010, fr1010 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1011, fk1011, fb1011, fr1011 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1012, fk1012, fb1012, fr1012 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1013, fk1013, fb1013, fr1013 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1014, fk1014, fb1014, fr1014 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1015, fk1015, fb1015, fr1015 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 11
fw1101, fk1101, fb1101, fr1101 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1102, fk1102, fb1102, fr1102 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1103, fk1103, fb1103, fr1103 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1104, fk1104, fb1104, fr1104 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1105, fk1105, fb1105, fr1105 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1106, fk1106, fb1106, fr1106 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1107, fk1107, fb1107, fr1107 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1108, fk1108, fb1108, fr1108 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1109, fk1109, fb1109, fr1109 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1110, fk1110, fb1110, fr1110 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1111, fk1111, fb1111, fr1111 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1112, fk1112, fb1112, fr1112 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1113, fk1113, fb1113, fr1113 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1114, fk1114, fb1114, fr1114 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1115, fk1115, fb1115, fr1115 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 12
fw1201, fk1201, fb1201, fr1201 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1202, fk1202, fb1202, fr1202 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1203, fk1203, fb1203, fr1203 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1204, fk1204, fb1204, fr1204 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1205, fk1205, fb1205, fr1205 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1206, fk1206, fb1206, fr1206 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1207, fk1207, fb1207, fr1207 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1208, fk1208, fb1208, fr1208 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1209, fk1209, fb1209, fr1209 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1210, fk1210, fb1210, fr1210 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1211, fk1211, fb1211, fr1211 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1212, fk1212, fb1212, fr1212 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1213, fk1213, fb1213, fr1213 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1214, fk1214, fb1214, fr1214 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1215, fk1215, fb1215, fr1215 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 13
fw1301, fk1301, fb1301, fr1301 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1302, fk1302, fb1302, fr1302 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1303, fk1303, fb1303, fr1303 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1304, fk1304, fb1304, fr1304 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1305, fk1305, fb1305, fr1305 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1306, fk1306, fb1306, fr1306 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1307, fk1307, fb1307, fr1307 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1308, fk1308, fb1308, fr1308 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1309, fk1309, fb1309, fr1309 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1310, fk1310, fb1310, fr1310 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1311, fk1311, fb1311, fr1311 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1312, fk1312, fb1312, fr1312 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1313, fk1313, fb1313, fr1313 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1314, fk1314, fb1314, fr1314 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1315, fk1315, fb1315, fr1315 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linnha 14
fw1401, fk1401, fb1401, fr1401 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1402, fk1402, fb1402, fr1402 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1403, fk1403, fb1403, fr1403 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1404, fk1404, fb1404, fr1404 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1405, fk1405, fb1405, fr1405 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1406, fk1406, fb1406, fr1406 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1407, fk1407, fb1407, fr1407 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1408, fk1408, fb1408, fr1408 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1409, fk1409, fb1409, fr1409 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1410, fk1410, fb1410, fr1410 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1411, fk1411, fb1411, fr1411 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1412, fk1412, fb1412, fr1412 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1413, fk1413, fb1413, fr1413 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1414, fk1414, fb1414, fr1414 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1415, fk1415, fb1415, fr1415 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 15
fw1501, fk1501, fb1501, fr1501 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1502, fk1502, fb1502, fr1502 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1503, fk1503, fb1503, fr1503 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1504, fk1504, fb1504, fr1504 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1505, fk1505, fb1505, fr1505 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1506, fk1506, fb1506, fr1506 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1507, fk1507, fb1507, fr1507 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1508, fk1508, fb1508, fr1508 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1509, fk1509, fb1509, fr1509 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1510, fk1510, fb1510, fr1510 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1511, fk1511, fb1511, fr1511 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1512, fk1512, fb1512, fr1512 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1513, fk1513, fb1513, fr1513 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1514, fk1514, fb1514, fr1514 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1515, fk1515, fb1515, fr1515 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 16
fw1601, fk1601, fb1601, fr1601 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1602, fk1602, fb1602, fr1602 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1603, fk1603, fb1603, fr1603 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1604, fk1604, fb1604, fr1604 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1605, fk1605, fb1605, fr1605 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1606, fk1606, fb1606, fr1606 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1607, fk1607, fb1607, fr1607 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1608, fk1608, fb1608, fr1608 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1609, fk1609, fb1609, fr1609 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1610, fk1610, fb1610, fr1610 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1611, fk1611, fb1611, fr1611 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1612, fk1612, fb1612, fr1612 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1613, fk1613, fb1613, fr1613 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1614, fk1614, fb1614, fr1614 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1615, fk1615, fb1615, fr1615 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 17
fw1701, fk1701, fb1701, fr1701 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1702, fk1702, fb1702, fr1702 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1703, fk1703, fb1703, fr1703 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1704, fk1704, fb1704, fr1704 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1705, fk1705, fb1705, fr1705 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1706, fk1706, fb1706, fr1706 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1707, fk1707, fb1707, fr1707 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1708, fk1708, fb1708, fr1708 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1709, fk1709, fb1709, fr1709 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1710, fk1710, fb1710, fr1710 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1711, fk1711, fb1711, fr1711 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1712, fk1712, fb1712, fr1712 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1713, fk1713, fb1713, fr1713 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1714, fk1714, fb1714, fr1714 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1715, fk1715, fb1715, fr1715 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)

#Atribuição dos pisos que podem ser desenhados na linha 18
fw1801, fk1801, fb1801, fr1801 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1802, fk1802, fb1802, fr1802 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1803, fk1803, fb1803, fr1803 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1804, fk1804, fb1804, fr1804 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1805, fk1805, fb1805, fr1805 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1806, fk1806, fb1806, fr1806 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1807, fk1807, fb1807, fr1807 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1808, fk1808, fb1808, fr1808 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1809, fk1809, fb1809, fr1809 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1810, fk1810, fb1810, fr1810 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1811, fk1811, fb1811, fr1811 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1812, fk1812, fb1812, fr1812 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1813, fk1813, fb1813, fr1813 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1814, fk1814, fb1814, fr1814 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
fw1815, fk1815, fb1815, fr1815 = PisoBranco(objectGroup, white_floorGroup), PisoPreto(objectGroup, black_floorGroup), PisoAzul(objectGroup, blue_floorGroup), PisoVermelho(objectGroup, red_floorGroup)
